### ISSUE TITLE
Particle effects activated in the particle manager and the map mode

### ISSUE THREAD

**Issue by Bertram25** [Bertram25/ValyriaTear#223]
Particle effects activated through the particle manager suffer inverted Y parallax effect when moving around in the map mode.

Since I don't explicitely add parallax to particle effects at all, I wonder how this is possible. The most funny is that it could be clearly cool, would the x and y parallax effects be not the reverse of what they should be.

Try moving around in the Mt Elbrus rainy maps ans you'll get what I mean.

Have you got any clue @logzero or @IkarusDowned?

**Comment by Bertram25** [comment]
@authenticate Have you got any idea of why this is happening, btw?
The new_map_code branch has a map mode converted to use standard coordinates as well as the map mode, so the coordsys isn't guilty.

On the other hand, I may easily miss something obvious.
I you don't see what it could come from, I'll close this issue as won't fix, since I've no idea for the moment about why.

For the record, you can easily see the bug when moving around a map with snow or rain. When moving up, the rain is falling slower, and when moving down it is falling faster.

**Comment by authenticate** [comment]
I am not immediately sure.  I'll take a look at the issue in game and browse some of the code to try and get a better idea.


In addition, I have noticed a very similar issue.  As the camera moves around the map, the cloud shadows are not drawn at the same location as when the character is stationary.

So, for example, if you rapidly change directions or go back and forth, the cloud shadows will almost jitter or jump.

I am not sure if this is related to the particle issue.  However, they seemed kind of related.

Hopefully I described the issue well enough for you to reproduce it.  It will only happen on a map large enough for the camera to pan with the main character.  That seems to be part of the root cause.

**Comment by Bertram25** [comment]
> Hopefully I described the issue well enough for you to reproduce it.

Yeah, I see what you're talking about. I didn't make a link between the two but now you tell it.
I wonder: I think the same issue can be seen on map objects when the camera is moving away from the character in certain scenes. You have to fall on such scene though, such as when Kalya sees the fallen tree.

**Comment by Bertram25** [comment]
Ok, closing this one as won't fix. If a more relevant and meaningful bug appears, I'll open a new issue.
