### ISSUE TITLE
Fedora build of 1.0.0 fails (after boost update?)

### ISSUE THREAD

**Issue by Ablu** [Bertram25/ValyriaTear#427]
Hello,

boost was updated in fedora and all packages depending on it got rebuilt. Now ValyriaTear failed to rebuild with this build log: http://koji.fedoraproject.org/koji/getfile?taskID=8730962&name=build.log

The errors somehow happen in the luabind headers. Does anyone know what the issue is there? Is it an issue in luabind or in Valyria Tear?

Regards,
Ablu

**Comment by Bertram25** [comment]
Hey @Ablu :)

Seems luabind needs an update to work with the latest boost libraries, indeed.
https://github.com/luabind/luabind/issues/27

This can be fixed with this commit:
https://github.com/Oberon00/luabind/commit/fb3c6623c728209a2ba69d178bd87589bf04e9cf

I'll import it asap.

Thanks for pointing out. :)

Btw, how is life going for you?

Best regards,

**Comment by Ablu** [comment]
Thanks for the solution. I will sync with the luabind maintainer to get
this fixed in fedora (I use the system luabind install).

- Sent from mobile. Please excuse shortness and typing errors. (Might be
sent delayed too)

**Comment by Bertram25** [comment]
Hopefully fixed with 76411d4dd3d82abaa4732cf7160e6a11ab79ac3e
