### ISSUE TITLE
The minimap is not scissored anymore.

### ISSUE THREAD

**Issue by Bertram25** [Bertram25/ValyriaTear#434]
Here is a visual look at the bug:
![screenshot_2](https://cloud.githubusercontent.com/assets/765917/6129906/cec73984-b141-11e4-8d7d-f4326d112e0a.png)

**Comment by Bertram25** [comment]
@authenticate Just for info. I've not looked at it yet, though but I think this might be linked to how we're now setting the viewport or anything similar.

**Comment by authenticate** [comment]
I was not able to reproduce this.  Is the issue linked to a certain map?  I checked a couple of forest maps near the village and the minimap seemed ok.

![minimap_test](https://cloud.githubusercontent.com/assets/4543259/6133694/cbc558f0-b129-11e4-9d2f-5b757e6b8fba.png)

**Comment by Bertram25** [comment]
Oh? Funny... Maybe it's linked to drivers or the platform?
@akien-mga I keep bothering you ;) Do you have such a problem on your own?

**Comment by akien-mga** [comment]
What is the cheat code to jump to a particular location? :-)
My only save games currently are high up in Mt Elbrus and there is no minimap there.

**Comment by Bertram25** [comment]
@akien-mga Ok, I'll send you a save.

**Comment by Bertram25** [comment]
> What is the cheat code to jump to a particular location? :-)

Btw, there are none, but I do create specific saves when needed. ;)

**Comment by Bertram25** [comment]
save is sent. :)

**Comment by akien-mga** [comment]
> save is sent. :)

Thanks! :) I have the same issue as @Bertram25 with the intel drivers (latest intel, latest mesa). Here's a video demonstrating the issue: http://remi.verschelde.fr/files/misc/VT-minimap.mkv

I'll try to see if I get the same error with my Nvidia GPU... though it tends to freeze my laptop since I updated to kernel 3.19.0, I hope it will work this time :-D

**Comment by akien-mga** [comment]
> I'll try to see if I get the same error with my Nvidia GPU... 

I confirm @Bertram25's guess, there is no issue with the proprietary nvidia driver, so it's a driver-related issue.

**Comment by Bertram25** [comment]
Oh my... Ok. Thanks for narrowing it down @akien-mga :)

**Comment by authenticate** [comment]
I did a quick look through the code and I think the only place where we use a clipping/scissors rectangle is in the text rendering.

So, as a work-around, it seems possible that we could add a clipping rectangle for the minimap.  The minimap appears to always be drawn in a specific location on the screen.  So, we should be able to calculate that position and the clip the image accordingly.

**Comment by Bertram25** [comment]
So you mean that this isn't meant to limit the screen rendering area?
Or is there something specific to the intel driver for that gl function?
https://github.com/Bertram25/ValyriaTear/blob/master/src/modes/map/map_minimap.cpp#L236
https://github.com/Bertram25/ValyriaTear/blob/master/src/engine/video/video.cpp#L636
https://www.khronos.org/opengles/sdk/docs/man/xhtml/glViewport.xml

**Comment by authenticate** [comment]
That's my mistake.  I didn't notice it before.

Yes. That's correct.  It should do what you want it to do.

However, as a side note, the viewport and scissor rectangle perform different but similar functions.  The viewport only clips triangles or, said differently, affects drawing operations.

So, if you cleared the render target, you would clear the entire render target and not just the viewport.

The scissor rectangle affects all operations (there may be some exceptions to this).  For example, you could use the scissor rectangle to only clear a subset of the render target.

So, adding a scissor rectangle could fix the issue.  I don't know if it actually will.  However, it shouldn't hurt anything.

**Comment by Bertram25** [comment]
Ok, thanks for precision. I'll keep that in mind. Do you think we should open an issue on the mesa bug tracker? (IMHO, it may not hurt.)

**Comment by authenticate** [comment]
You could if you want to.

However, I think it would be very hard to provide a clear and concise bug report.  The problem is that the OpenGL specification is extremely complex.  Where exactly is the problem?  That's a hard question.

It is entirely possible that the drivers are actually correct.

A similar thing happened with the black screen Intel shader issue.  The Intel drivers were actually correct in drawing a black screen.  The shader code was incorrect.

Now, nVidia's implementation was robust enough to essentially "do what the programmer intends" and render the game.  However, that doesn't make Intel's implementation wrong.

A similar thing could be happening here.  I don't really know nor know how to prove or detect it. :(

If you have any extra time or are interested, it might be worth glancing at

http://github.com/ValveSoftware/Dota-2/

particularly, the Intel related information. 

Recently, I know Valve helped fix many Linux OpenGL driver related issues across all GPU vendors while shipping DOTA 2 for Ubuntu.  I would check to see if your mesa version is compatible with running DOTA 2.  If the driver can run DOTA 2, the error is most likely on our end.

**Comment by Bertram25** [comment]
Ok, I'll have a go at installing DOTA2 and have a good excuse for a few games there. ;)
Thanks for all the info.

Btw, this issue is fixed thanks to aa8dc4ab31c4df71dc23f49ab614f561d979a47e
