### ISSUE TITLE
High-bouncing numbers against Dorver (spike cave)

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#453]
I saw high-bouncing numbers against Dorver again (spike cave). There wasn't really anything weird prior to the fight with him, though I hadn't battled in awhile. After pausing and unpausing the battle, the numbers bounced normally.

This was observed after 10a1ac7 (the fix for #445)

**Comment by Bertram25** [comment]
Funny. I think my fix isn't enough then. I'll have another look. ;)

**Comment by Bertram25** [comment]
Again, after pausing the game for more than one hour, the bug didn't happen.
Could you log the update time after pausing the game seen in https://github.com/Bertram25/ValyriaTear/commit/10a1ac7b40e66239d5e84f05a6baf955675b496b ? It would help understand whether the bug is from there or not. (I'll also need your help on that one, unfortunately.)
