### ISSUE TITLE
Weird orange glow above save point in mt elbrus

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#454]
There's a weird, full-screen orange glow directly above the save point in mt elbrus (the one with the cat next to the statue). It kinda flickers as you walk through it, and gradually disappears as you walk left toward Sophia.

![no-glow](https://cloud.githubusercontent.com/assets/1323568/6576375/36468a2a-c70d-11e4-9e3f-bdfecc02ce6e.PNG)
![red-glow](https://cloud.githubusercontent.com/assets/1323568/6576376/3647de02-c70d-11e4-928e-8f18ccd22f9c.PNG)

**Comment by Bertram25** [comment]
lol XD I'll have a look.

**Comment by Bertram25** [comment]
Sorry, this is all development refactoring glitches. I hope you won't end hating the game for such ones. ;)

**Comment by Suitecake** [comment]
It's fine! There are other things I can work on if a crash is a blocker for testing the rush feature (only the map transition crashes atm). These things are part of development, no worries.

Some of them are pretty fun to run into. The high-bouncing numbers are a great quirk =p

**Comment by Bertram25** [comment]
I think you have something weird on your side. The orange stuff is the light layer which is supposed to surround the little flames in your screenshots, like this:
![screenshot_1](https://cloud.githubusercontent.com/assets/765917/6587052/9c292a92-c77f-11e4-8dc6-efae2278cd99.png)
Is the bug systematic or is it happening after a specific event?

**Comment by Bertram25** [comment]
@Suitecake Btw, since we are using FFP shaders now, there could be corrupted vertexes happening when drawing the lights. I'll test the compilation with C::B on windows asap to see whether this is something coming from drivers/os maybe and try later on MSVC.

IIRC, you're compiling VT under MSVC2013, right? Sorry in advance for the basicness of the questions:
- What is your os? graphic card? Driver version?
- How do you compile VT?

Best regards, :)

**Comment by Bertram25** [comment]
I was able to reproduce! :D 
The "bug" happens only when you just made the door open. I'll investigate.
